logging:
  level:
    ROOT: info
    org.hibernate.SQL: DEBUG
    com.vibrix: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: vibrix-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${postgres_url}:5432/${postgres_db}
    username: ${postgres_username}
    password: ${postgres_password}
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: vibrix
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: vibrix
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-luw2u4jhcbu0ukq3.us.auth0.com/
    client-id: ${auth0_client_id}
    client-secret: ${auth0_client_secret}
